### ISSUE TITLE
custom Vamp ES/LS container package for DC/OS doesn't work in DCOS 1.8.x

### ISSUE THREAD

**Issue by olafmol** [magneticio/elastic#1]
only spins up executor, not slaves. 
Regular ES universe package does work, generates this JSON:

```
{
  "mesos": {
    "master": "zk://master.mesos:2181/mesos"
  },
  "elasticsearch": {
    "framework-name": "elasticsearch",
    "failover-timeout": "2592000.0",
    "zookeeper-mesos-timeout": "20000",
    "port": "31105",
    "force-pull-image": true,
    "executor": {
      "ram": "2048",
      "cpu": "1.0",
      "disk": "1024",
      "instances": "3",
      "cluster-name": "mesos-ha",
      "name": "elasticsearch-executor"
    },
    "scheduler": {
      "cpu": "0.2",
      "ram": "512",
      "instances": "1",
      "java-heap": "-Xms128m -Xmx256m"
    }
  }
}

**Comment by iamtew** [comment]
I'm working on this.

**Comment by iamtew** [comment]
@olafmol where do you get that JSON object from?

**Comment by olafmol** [comment]
that's exactly how i did it (installed through the DCOS universe package, and download the generated JSON)

**Comment by iamtew** [comment]
This has been fixed by moving away from the `mesos/elasticsearch-executor` image and using only our own, `magneticio/elastic:2.2`. 

See:
- https://github.com/magneticio/revamp.io/commit/f3401862d94563157fc6ab8ccda425e0996f3112#diff-a34608ebd14808befd586fe99b3da8adR51
- https://github.com/magneticio/revamp.io/issues/103#issuecomment-250753061
